import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import {
  consolidateMetaFacts, conversationsOf, defaultRegionProject, leadsOf, metaFacts, metaMonthRange,
  metaRegionRules, reachNote, regionLabel, splitRegionsByProject,
  toMetaDay, toMetaPeriod, toMetaRegionDay, withFxRate, type MetaInsightRow,
} from "../lib/meta.ts";

/**
 * Synthetic insights shaped like Meta's, generated by `outputs/make-synthetic-fixture.mjs`.
 * This repository is public, so the fixture carries no real advertising figures — only the
 * properties the code depends on: daily spend reconciles to the monthly row, the monthly reach
 * is far below the sum of the daily reach, and the regional rows need six decimals to add up.
 */
const fixture = JSON.parse(readFileSync(new URL("./fixtures/meta-august.json", import.meta.url), "utf8")) as {
  accountId: string;
  daily: MetaInsightRow[];
  monthly: MetaInsightRow[];
  regionsOneDay: MetaInsightRow[];
};
const ACC = fixture.accountId;
const days = fixture.daily.map(r => toMetaDay(ACC, r)!);
const periods = fixture.monthly.map(r => toMetaPeriod(ACC, r)!);

test("an insights row becomes a day, keeping only the metrics the funnel uses", () => {
  const row: MetaInsightRow = {
    date_start: "2026-08-03", date_stop: "2026-08-03", spend: "225.41", impressions: "43011", reach: "29811",
    clicks: "693", inline_link_clicks: "455", unique_inline_link_clicks: "372",
    actions: [
      { action_type: "onsite_conversion.post_save", value: "120" },
      { action_type: "landing_page_view", value: "190" },
      { action_type: "onsite_conversion.messaging_conversation_started_7d", value: "135" },
      { action_type: "lead", value: "2" },
    ],
  };
  assert.deepEqual(toMetaDay(ACC, row), {
    accountId: ACC, date: "2026-08-03", spend: 225.41, impressions: 43011, reach: 29811, clicks: 693,
    linkClicks: 455, linkClickPeople: 372, landingViews: 190, conversations: 135, leads: 2,
  });
  assert.equal(conversationsOf(row.actions), 135);
  assert.equal(leadsOf(row.actions), 2);
  // A row with no date is not a day.
  assert.equal(toMetaDay(ACC, { spend: "1" }), null);
  // Saves, likes and comments are engagement, not leads.
  assert.equal(leadsOf([{ action_type: "onsite_conversion.post_save", value: "9" }]), 0);
  // Meta sometimes serves the link click only as an action; that form is read too.
  assert.equal(toMetaDay(ACC, { date_start: "2026-08-03", actions: [{ action_type: "link_click", value: "40" }] })!.linkClicks, 40);
});

test("a whole month: spend adds up across days, reach does not", () => {
  const facts = metaFacts(days, periods)!;
  const month = periods[0]!;
  assert.equal(days.length, 31);
  // Spend is money: the daily rows must reconcile to Meta's own monthly figure to the cent.
  assert.equal(facts.spend, month.spend);
  assert.equal(facts.impressions, month.impressions);
  assert.equal(facts.clicks, month.clicks);
  // Reach counts people. The window is exactly the month Meta aggregated, so its own number is used…
  assert.equal(facts.reach, month.reach);
  // …and it is far below the sum of the daily rows, because the same person is reached on many days.
  assert.equal(facts.reachDays, days.reduce((a, d) => a + d.reach, 0));
  assert.ok(facts.reachDays > facts.reach! * 2);
  assert.equal(facts.days, 31);
  assert.deepEqual([facts.firstDate, facts.lastDate], ["2026-08-01", "2026-08-31"]);
  assert.deepEqual(facts.accounts, [ACC]);
});

test("a part-month window refuses to report a people count", () => {
  const firstWeek = days.filter(d => d.date <= "2026-08-07");
  const facts = metaFacts(firstWeek, periods)!;
  assert.equal(facts.days, 7);
  // Meta only deduplicates reach for the periods it aggregated; a week inside a month is not one of them.
  assert.equal(facts.reach, null);
  assert.equal(facts.frequency, null);
  assert.ok(facts.reachDays > 0);
  assert.match(reachNote(facts), /көрсетілім-күн/);
  // Money is still exact for any window.
  assert.equal(facts.spend, Math.round(firstWeek.reduce((a, d) => a + d.spend, 0) * 100) / 100);
});

test("without a rate the tenge figure stays empty, never zero", () => {
  const facts = metaFacts(days, periods)!;
  const unknown = withFxRate(facts, null)!;
  assert.equal(unknown.spendKzt, null);
  assert.equal(unknown.fxRate, null);
  const priced = withFxRate(facts, 450.91)!;
  assert.equal(priced.fxRate, 450.91);
  assert.equal(priced.spendKzt, Math.round(facts.spend * 450.91));
  // A nonsense rate is treated as no rate.
  assert.equal(withFxRate(facts, 0)!.spendKzt, null);
  assert.equal(withFxRate(null, 450.91), null);
});

test("cost metrics come from the window's own totals", () => {
  const facts = metaFacts(days, periods)!;
  assert.equal(facts.cpm, Math.round((facts.spend / facts.impressions) * 1000 * 100) / 100);
  assert.equal(facts.cpc, facts.spend / facts.clicks);
  // CTR counts the link click, not a like or a comment.
  assert.equal(facts.ctr, facts.linkClicks / facts.impressions);
  assert.equal(facts.costPerConversation, facts.spend / facts.conversations);
  assert.equal(metaFacts([]), null);
});

test("consolidating projects sums money but never sums people", () => {
  const half = Math.ceil(days.length / 2);
  const a = withFxRate(metaFacts(days.slice(0, half), periods), 450.91)!;
  const b = withFxRate(metaFacts(days.slice(half), periods), 450.91)!;
  const total = consolidateMetaFacts([a, b])!;
  assert.equal(total.spend, periods[0]!.spend);
  assert.equal(total.spendKzt, a.spendKzt! + b.spendKzt!);
  assert.equal(total.fxRate, 450.91);
  // Two projects' audiences overlap, so a summed reach would be a lie.
  assert.equal(total.reach, null);
  assert.equal(total.reachDays, a.reachDays + b.reachDays);

  // A total that is missing one project's rate is not a total.
  const noRate = consolidateMetaFacts([a, withFxRate(b, null)!])!;
  assert.equal(noRate.spendKzt, null);
  // Mixed rates cannot be shown as one rate.
  assert.equal(consolidateMetaFacts([a, withFxRate(b, 500)!])!.fxRate, null);
  assert.equal(consolidateMetaFacts([null, null]), null);
});

test("the regional split accounts for every dollar of the day", () => {
  const rows = fixture.regionsOneDay.map(r => toMetaRegionDay(ACC, r)!);
  assert.equal(rows.length, 15);
  // Meta apportions the day's spend with six decimals. Rounding each region to cents first would
  // give 490.19 — a cent more than the day actually cost — so the rounding happens after summing.
  assert.equal(Math.round(rows.reduce((a, r) => a + r.spend, 0) * 100) / 100, 490.18);
  assert.notEqual(Math.round(rows.reduce((a, r) => a + Math.round(r.spend * 100) / 100, 0) * 100) / 100, 490.18);
  assert.ok(rows.every(r => r.date === "2026-09-14" && r.region));
  // A row without a region is not a regional row.
  assert.equal(toMetaRegionDay(ACC, { date_start: "2026-09-14", spend: "1" }), null);
  assert.equal(regionLabel("Jambyl Region"), "Жамбыл (Тараз)");
  assert.equal(regionLabel("Mars"), "Mars");
});

test("a month range covers the whole month, February included", () => {
  assert.deepEqual(metaMonthRange("2026-08"), { from: "2026-08-01", to: "2026-08-31" });
  assert.deepEqual(metaMonthRange("2026-09"), { from: "2026-09-01", to: "2026-09-30" });
  assert.deepEqual(metaMonthRange("2026-02"), { from: "2026-02-01", to: "2026-02-28" });
  assert.deepEqual(metaMonthRange("2028-02"), { from: "2028-02-01", to: "2028-02-29" });
});

test("the reach note says which of the two numbers it is", () => {
  const whole = metaFacts(days, periods)!;
  assert.match(reachNote(whole), /адам/);
  assert.match(reachNote(whole), /бір адамды бір рет/);
  // The note carries the month's own count, not the sum of days.
  assert.ok(reachNote(whole).includes(periods[0]!.reach.toLocaleString("ru-RU")));
  assert.ok(!reachNote(whole).includes("көрсетілім-күн"));
});

const PROJECTS = [
  { id: "workspace-main", name: "EdUser" },
  { id: "tl", name: "TamshyLab" },
  { id: "tz", name: "Тараз Едусер" },
  { id: "kz", name: "Қызылорда Едусер" },
];

test("a region goes to the project named after its city, everything else to the main one", () => {
  const of = (region: string) => defaultRegionProject(region, PROJECTS, "workspace-main");
  assert.equal(of("Jambyl Region"), "tz");
  assert.equal(of("Kyzylorda Region"), "kz");
  // Astana is inside Akmola in Meta's list, and the online business takes those sales.
  assert.equal(of("Akmola Region"), "workspace-main");
  assert.equal(of("South Kazakhstan Region"), "workspace-main");
  // Ads also run abroad; that spend belongs to the online project too.
  assert.equal(of("Dubai"), "workspace-main");
  assert.equal(of("Unknown"), "workspace-main");
  // Kazakh spelling is folded, so «Қызылорда Едусер» is found by «кызылорда».
  assert.equal(defaultRegionProject("Kyzylorda Region", [{ id: "x", name: "ҚЫЗЫЛОРДА ЕДУСЕР" }], "nope"), "x");
  // With no project named after the city the spend is not guessed onto another project.
  assert.equal(defaultRegionProject("Jambyl Region", [{ id: "only", name: "EdUser" }], "only"), null);
});

test("the owner's region choice overrides the default and can be taken back", () => {
  const seen = ["Jambyl Region", "Dubai"];
  const plain = metaRegionRules(seen, PROJECTS, "workspace-main");
  assert.equal(plain.find(r => r.region === "Dubai")!.projectId, "workspace-main");
  assert.equal(plain.find(r => r.region === "Dubai")!.builtin, true);

  const moved = metaRegionRules(seen, PROJECTS, "workspace-main", [{ region: "Dubai", projectId: "tl" }]);
  const dubai = moved.find(r => r.region === "Dubai")!;
  assert.equal(dubai.projectId, "tl");
  assert.equal(dubai.builtin, false);

  // «Жобасыз» is a real choice, not a missing one: that spend reaches no project.
  const excluded = metaRegionRules(seen, PROJECTS, "workspace-main", [{ region: "Dubai", projectId: null }]);
  assert.equal(excluded.find(r => r.region === "Dubai")!.projectId, null);
  assert.equal(excluded.find(r => r.region === "Dubai")!.builtin, false);
  // Kazakhstan's regions are always listed, even before any spend has reached them.
  assert.ok(plain.some(r => r.region === "Mangystau Region"));
});

test("splitting by region keeps every cent and sets aside what belongs to nobody", () => {
  const rows = fixture.regionsOneDay.map(r => toMetaRegionDay(ACC, r)!);
  const rules = metaRegionRules(rows.map(r => r.region), PROJECTS, "workspace-main");
  const { byProject, unassigned } = splitRegionsByProject(rows, rules);
  const total = Math.round(rows.reduce((a, r) => a + r.spend, 0) * 100) / 100;
  const parts = [...byProject.values()].flat().reduce((a, p) => a + p.amount, 0);
  assert.equal(Math.round((parts + unassigned) * 100) / 100, total);
  assert.equal(unassigned, 0);
  // Тараз and Қызылорда each get their own region and nothing else.
  assert.equal(byProject.get("tz")!.length, 1);
  assert.equal(byProject.get("kz")!.length, 1);
  assert.equal(byProject.get("tz")![0]!.amount, rows.find(r => r.region === "Jambyl Region")!.spend);

  // A region sent nowhere is held back instead of being spread over the others.
  const excluded = metaRegionRules(rows.map(r => r.region), PROJECTS, "workspace-main", [{ region: "Jambyl Region", projectId: null }]);
  const second = splitRegionsByProject(rows, excluded);
  assert.equal(second.byProject.has("tz"), false);
  assert.equal(second.unassigned, rows.find(r => r.region === "Jambyl Region")!.spend);
});

test("spend converts day by day, and a whole month's manual rate wins over the daily ones", async () => {
  const { rateLookup } = await import("../lib/fx.ts");
  const daily = [{ day: "2026-08-01", rate: 462 }, { day: "2026-08-02", rate: 464 }];
  const plain = rateLookup(daily, []);
  assert.equal(plain("2026-08-01"), 462);
  assert.equal(plain("2026-08-02"), 464);
  assert.equal(plain("2026-08-03"), null);

  // The owner's figure for the month replaces every day in it, including days with no official rate.
  const overridden = rateLookup(daily, [{ period: "2026-08", rate: 450.91 }]);
  assert.equal(overridden("2026-08-01"), 450.91);
  assert.equal(overridden("2026-08-03"), 450.91);
  assert.equal(overridden("2026-09-01"), null);
});

test("a month of real days converts to tenge at each day's own rate", () => {
  // Rates fall through the year, so a flat rate would misstate the month.
  const rateOf = (day: string) => 470 - Number(day.slice(8)) * 0.5;
  const facts = metaFacts(days, periods, rateOf)!;
  const expected = Math.round(days.reduce((a, d) => a + d.spend * rateOf(d.date), 0));
  assert.equal(facts.spendKzt, expected);
  assert.deepEqual(facts.missingRateDays, []);
  assert.ok(facts.fxRate! > 454 && facts.fxRate! < 470);

  // One day without a rate empties the tenge figure and names the day.
  const gapped = metaFacts(days, periods, day => (day === "2026-08-15" ? null : 460))!;
  assert.equal(gapped.spendKzt, null);
  assert.deepEqual(gapped.missingRateDays, ["2026-08-15"]);
  // The dollar figure is unaffected: only the conversion is unknown.
  assert.equal(gapped.spend, facts.spend);
});

test("the traffic steps: clicks add up, the people behind them do not", () => {
  const facts = metaFacts(days, periods)!;
  const month = periods[0]!;
  // Link clicks are events, so the daily rows reconcile to the month.
  assert.equal(facts.linkClicks, month.linkClicks);
  assert.equal(facts.linkClicks, days.reduce((a, d) => a + d.linkClicks, 0));
  assert.equal(facts.landingViews, days.reduce((a, d) => a + d.landingViews, 0));
  // Unique clickers count people: the month's figure is far below the sum of its days.
  assert.equal(facts.linkClickPeople, month.linkClickPeople);
  assert.equal(facts.linkClickPeopleDays, days.reduce((a, d) => a + d.linkClickPeople, 0));
  assert.ok(facts.linkClickPeopleDays > facts.linkClickPeople! * 2);
  // Fewer people arrive than click, which is the whole point of tracking both.
  assert.ok(facts.landingViews < facts.linkClicks);

  // CTR is the link click, not every click: a like is not a visit.
  assert.equal(facts.ctr, facts.linkClicks / facts.impressions);
  assert.ok(facts.clicks > facts.linkClicks);
  assert.equal(facts.landingRate, facts.landingViews / facts.linkClicks);
  assert.equal(facts.costPerLinkClick, facts.spend / facts.linkClicks);
  assert.equal(facts.costPerLandingView, facts.spend / facts.landingViews);
});

test("a part-month window gives no people count for link clicks either", () => {
  const week = days.filter(d => d.date <= "2026-08-07");
  const facts = metaFacts(week, periods)!;
  assert.equal(facts.linkClickPeople, null);
  assert.ok(facts.linkClickPeopleDays > 0);
  // The event counts stay exact for any window.
  assert.equal(facts.linkClicks, week.reduce((a, d) => a + d.linkClicks, 0));
});

test("pooling projects adds the events and drops the people", () => {
  const half = Math.ceil(days.length / 2);
  const a = metaFacts(days.slice(0, half), periods)!;
  const b = metaFacts(days.slice(half), periods)!;
  const total = consolidateMetaFacts([a, b])!;
  assert.equal(total.linkClicks, a.linkClicks + b.linkClicks);
  assert.equal(total.landingViews, a.landingViews + b.landingViews);
  assert.equal(total.linkClickPeople, null);
  assert.equal(total.linkClickPeopleDays, a.linkClickPeopleDays + b.linkClickPeopleDays);
});
