import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import {
  consolidateMetaFacts, conversationsOf, leadsOf, metaFacts, metaMonthRange, reachNote, regionLabel,
  toMetaDay, toMetaPeriod, toMetaRegionDay, withFxRate, type MetaInsightRow,
} from "../lib/meta.ts";

/**
 * Synthetic insights shaped like Meta's, generated by `outputs/make-synthetic-fixture.mjs`.
 * This repository is public, so the fixture carries no real advertising figures — only the
 * properties the code depends on: daily spend reconciles to the monthly row, the monthly reach
 * is far below the sum of the daily reach, and the regional rows need six decimals to add up.
 */
const fixture = JSON.parse(readFileSync(new URL("./fixtures/meta-august.json", import.meta.url), "utf8")) as {
  accountId: string;
  daily: MetaInsightRow[];
  monthly: MetaInsightRow[];
  regionsOneDay: MetaInsightRow[];
};
const ACC = fixture.accountId;
const days = fixture.daily.map(r => toMetaDay(ACC, r)!);
const periods = fixture.monthly.map(r => toMetaPeriod(ACC, r)!);

test("an insights row becomes a day, with only the two actions the funnel uses", () => {
  const row: MetaInsightRow = {
    date_start: "2026-08-03", date_stop: "2026-08-03", spend: "225.41", impressions: "43011", reach: "29811", clicks: "693",
    actions: [
      { action_type: "onsite_conversion.post_save", value: "120" },
      { action_type: "onsite_conversion.messaging_conversation_started_7d", value: "135" },
      { action_type: "lead", value: "2" },
    ],
  };
  assert.deepEqual(toMetaDay(ACC, row), {
    accountId: ACC, date: "2026-08-03", spend: 225.41, impressions: 43011, reach: 29811, clicks: 693, conversations: 135, leads: 2,
  });
  assert.equal(conversationsOf(row.actions), 135);
  assert.equal(leadsOf(row.actions), 2);
  // A row with no date is not a day.
  assert.equal(toMetaDay(ACC, { spend: "1" }), null);
  // Saves, likes and comments are engagement, not leads.
  assert.equal(leadsOf([{ action_type: "onsite_conversion.post_save", value: "9" }]), 0);
});

test("a whole month: spend adds up across days, reach does not", () => {
  const facts = metaFacts(days, periods)!;
  const month = periods[0]!;
  assert.equal(days.length, 31);
  // Spend is money: the daily rows must reconcile to Meta's own monthly figure to the cent.
  assert.equal(facts.spend, month.spend);
  assert.equal(facts.impressions, month.impressions);
  assert.equal(facts.clicks, month.clicks);
  // Reach counts people. The window is exactly the month Meta aggregated, so its own number is used…
  assert.equal(facts.reach, month.reach);
  // …and it is far below the sum of the daily rows, because the same person is reached on many days.
  assert.equal(facts.reachDays, days.reduce((a, d) => a + d.reach, 0));
  assert.ok(facts.reachDays > facts.reach! * 2);
  assert.equal(facts.days, 31);
  assert.deepEqual([facts.firstDate, facts.lastDate], ["2026-08-01", "2026-08-31"]);
  assert.deepEqual(facts.accounts, [ACC]);
});

test("a part-month window refuses to report a people count", () => {
  const firstWeek = days.filter(d => d.date <= "2026-08-07");
  const facts = metaFacts(firstWeek, periods)!;
  assert.equal(facts.days, 7);
  // Meta only deduplicates reach for the periods it aggregated; a week inside a month is not one of them.
  assert.equal(facts.reach, null);
  assert.equal(facts.frequency, null);
  assert.ok(facts.reachDays > 0);
  assert.match(reachNote(facts), /көрсетілім-күн/);
  // Money is still exact for any window.
  assert.equal(facts.spend, Math.round(firstWeek.reduce((a, d) => a + d.spend, 0) * 100) / 100);
});

test("without a rate the tenge figure stays empty, never zero", () => {
  const facts = metaFacts(days, periods)!;
  const unknown = withFxRate(facts, null)!;
  assert.equal(unknown.spendKzt, null);
  assert.equal(unknown.fxRate, null);
  const priced = withFxRate(facts, 450.91)!;
  assert.equal(priced.fxRate, 450.91);
  assert.equal(priced.spendKzt, Math.round(facts.spend * 450.91));
  // A nonsense rate is treated as no rate.
  assert.equal(withFxRate(facts, 0)!.spendKzt, null);
  assert.equal(withFxRate(null, 450.91), null);
});

test("cost metrics come from the window's own totals", () => {
  const facts = metaFacts(days, periods)!;
  assert.equal(facts.cpm, Math.round((facts.spend / facts.impressions) * 1000 * 100) / 100);
  assert.equal(facts.cpc, facts.spend / facts.clicks);
  assert.equal(facts.ctr, facts.clicks / facts.impressions);
  assert.equal(facts.costPerConversation, facts.spend / facts.conversations);
  assert.equal(metaFacts([]), null);
});

test("consolidating projects sums money but never sums people", () => {
  const half = Math.ceil(days.length / 2);
  const a = withFxRate(metaFacts(days.slice(0, half), periods), 450.91)!;
  const b = withFxRate(metaFacts(days.slice(half), periods), 450.91)!;
  const total = consolidateMetaFacts([a, b])!;
  assert.equal(total.spend, periods[0]!.spend);
  assert.equal(total.spendKzt, a.spendKzt! + b.spendKzt!);
  assert.equal(total.fxRate, 450.91);
  // Two projects' audiences overlap, so a summed reach would be a lie.
  assert.equal(total.reach, null);
  assert.equal(total.reachDays, a.reachDays + b.reachDays);

  // A total that is missing one project's rate is not a total.
  const noRate = consolidateMetaFacts([a, withFxRate(b, null)!])!;
  assert.equal(noRate.spendKzt, null);
  // Mixed rates cannot be shown as one rate.
  assert.equal(consolidateMetaFacts([a, withFxRate(b, 500)!])!.fxRate, null);
  assert.equal(consolidateMetaFacts([null, null]), null);
});

test("the regional split accounts for every dollar of the day", () => {
  const rows = fixture.regionsOneDay.map(r => toMetaRegionDay(ACC, r)!);
  assert.equal(rows.length, 15);
  // Meta apportions the day's spend with six decimals. Rounding each region to cents first would
  // give 490.19 — a cent more than the day actually cost — so the rounding happens after summing.
  assert.equal(Math.round(rows.reduce((a, r) => a + r.spend, 0) * 100) / 100, 490.18);
  assert.notEqual(Math.round(rows.reduce((a, r) => a + Math.round(r.spend * 100) / 100, 0) * 100) / 100, 490.18);
  assert.ok(rows.every(r => r.date === "2026-09-14" && r.region));
  // A row without a region is not a regional row.
  assert.equal(toMetaRegionDay(ACC, { date_start: "2026-09-14", spend: "1" }), null);
  assert.equal(regionLabel("Jambyl Region"), "Жамбыл (Тараз)");
  assert.equal(regionLabel("Mars"), "Mars");
});

test("a month range covers the whole month, February included", () => {
  assert.deepEqual(metaMonthRange("2026-08"), { from: "2026-08-01", to: "2026-08-31" });
  assert.deepEqual(metaMonthRange("2026-09"), { from: "2026-09-01", to: "2026-09-30" });
  assert.deepEqual(metaMonthRange("2026-02"), { from: "2026-02-01", to: "2026-02-28" });
  assert.deepEqual(metaMonthRange("2028-02"), { from: "2028-02-01", to: "2028-02-29" });
});

test("the reach note says which of the two numbers it is", () => {
  const whole = metaFacts(days, periods)!;
  assert.match(reachNote(whole), /адам/);
  assert.match(reachNote(whole), /бір адамды бір рет/);
  // The note carries the month's own count, not the sum of days.
  assert.ok(reachNote(whole).includes(periods[0]!.reach.toLocaleString("ru-RU")));
  assert.ok(!reachNote(whole).includes("көрсетілім-күн"));
});
